### ISSUE TITLE
Remove single quotes from Kubernetes resource outputs

### ISSUE THREAD

**Issue by vdice** [getporter/helm-mixin#71]
Assuming the issue filed in https://github.com/deislabs/porter/issues/1210 is determined to be a bug we wish to fix, incorporate the same fix into this mixin.

Ref https://github.com/deislabs/porter/issues/1210

**Comment by vdice** [comment]
I think the preferred way to do this would be to refactor the applicable logic to consume the `getOutput` logic from `pkg/kubernetes/kubernetes.go` in deislabs/porter, so that this logic can be maintained/updated from the same location.

**Comment by carolynvs** [comment]
See https://github.com/getporter/porter/pull/1227/files#diff-ee3f112df3df9e8ec5f3f9f98618987fR97 for the final fix
